### ISSUE TITLE
Contribution to the project

### ISSUE THREAD

**Issue by Autoradiowecker** [magols/BlazorGPT#6]
Hi Magols,

are you stile working on the Project?

We forked this Repository around one month ago and made some changes. 
Are you interested in connecting to use and checking them out?

We changed the following things:
1.  Changed Authentication to Azure Login
2.  Changed the design of the layout a bit
3. Changed the way some components refresh their state. (we saw the script tab in the conversation, only realized it changed state after the Window Size of the components changed.)

Looking forward to your response,
Autoradiowecker

**Comment by magols** [comment]
Hi, and sorry for the very late reply.

Nice that you found some use of the code.

I am working on it from time to time. During the summer (or since MS Build 2023 really) I have been interested in Microsoft Semantic Kernel so I have replaced some parts of the application to hopefully be able to use it as a platform also for OpenAI plugins and Microsoft Copilots.

This has been living in the semantic-kernel branch for a while but now it is merged into the main branch.

I don't really know how compatible this is with your plans at all.
