### ISSUE TITLE
.NET 8 build fails

### ISSUE THREAD

**Issue by jarleholt** [magols/BlazorGPT#8]
What a great project! 

I have spent some hours trying to make it work, but it seems to not play well with .NET 8. I hope you can make a .NET 8 compatible version. I am not sufficiently competent to do it myself.

C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of
 .NET. See: https://aka.ms/dotnet-support-policy [C:\Users\Jarleh\Documents\GitHub\BlazorGPT\src\BlazorGPT\BlazorGPT.csproj]
C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\Microsoft.Common.CurrentVersion.targets(3327,5): error MSB3552: Resource file "**/*.resx" cannot be found. [C:\Users\Jarleh\Documents\GitHub\B
lazorGPT\src\BlazorGPT\BlazorGPT.csproj]

Build FAILED.

**Comment by magols** [comment]
Hello!

I have been using .NET 8 since the first previews and I have not had any problems related to the upcoming version.

The aspnetcore-related nuget dependencies in the project right now targeted preview-7 in the master branch. I have RC1 installed on my local machine and it works. I updated the branch now to target RC1 wherever applicable. You can pull the latest version perhaps and try.

That being said, the error you get seems to indicate something with resource files in the build process and not with the version at all. But the solution does not use resource files (resx) so I am not sure of what the problem can be. I will try to investigate further

**Comment by magols** [comment]
Closing this as stale
